server:
  port: 84

spring:
  application:
    name: travel-web-client
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
        client-ip: localhost
  thymeleaf:
    cache: true
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 200
        min-idle: 5
        max-wait: 10000ms
     #服务器地址
    host: 1.14.109.248
    port: 6379
#    cluster:
#      nodes: ['192.168.10.129:6379','192.168.10.129:6380','192.168.10.129:6381']
#      max-redirects: 5

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  naos-user-service: http://travel-server-client-route

management:
  endpoints:
    web:
      exposure:
        include: '*'

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true